[ubuntu-22-04]
pkgs = ["build-essential", "meson", "ninja-build", "python3-venv", "git", "pip", "libboost-dev", "libboost-python-dev", "libboost-thread-dev", "libasound2-dev", "libjack-dev"]

[fedora]
pkgs = ["meson", "ninja", "python3-pip", "boost-devel", "boost-python-devel", "gcc", "python3-devel", "alsa-lib-devel"]

[mint-21]
pkgs = ["build-essential", "meson", "ninja-build", "git", "python3-venv", "libboost-dev", "libboost-python-dev", "libasound2-dev", "libjack-dev"]

[arch]
pkgs = ["base-devel", "meson", "ninja", "git", "python-pip", "python-virtualenv", "boost", "alsa-lib", "jack2"]
